# main text of home
title: Jim Jing
bio: Neuroscience Researcher | AI Enthusiast | Science Writer
motto: "Standing on the bridge between AI and neuroscience, gazing into the mysteries of the brain"

# site description
description: A personal academic website focusing on neuroscience research and artificial intelligence

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/self_picture.jpg

# site color theme - true: dark theme, false: light theme, auto: system settings
dark-theme: auto

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: false
resume-url: resume

# GitHub Pages configuration
url: https://junlinjing.github.io
baseurl: /jjing-neuro

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
future: true

# Posts location
source: .
posts_dir: blog/_posts

# GitHub Pages settings
github: [metadata]
lsi: true
safe: true
incremental: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Local development configuration (uncomment when needed)
#url: http://localhost:4000
#baseurl: ""

# Social links
twitter: JimJing1997
linkedin: jjunlin
github_username: JunlinJing
email: jjunlin197@163.com

# Academic links
googlescholar: citations?user=XXXXX # Replace with your actual Google Scholar ID
researchgate: Junlin-Jing
orcid: 0009-0006-1290-7445

# Website author information
authors:
  jimjing:
    name: Jim Jing
    bio: Neuroscience Researcher | AI Enthusiast | Science Writer
    external-image: false
    picture: assets/images/self_picture.jpg
    twitter: JimJing1997

# Site width
width: large

# Pagination
pagination:
  enabled: true
  sort_reverse: true
  per_page: 10
  permalink: /page/:num/

# Pages
projects: true
publications: true
research: true
teaching: false
about: true
blog: true

# Post settings
read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true

# Jekyll plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# HTML compression
compress_html:
  ignore:
    envs:
      - development
      - stage

# Include and exclude
include:
  - _pages
  - .nojekyll

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - .git/
  - .github/
  - .gitignore
  - .DS_Store
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# RSS Feed configuration
feed:
  path: feed.xml
  posts_limit: 20
  categories:
    - news
    - blog
  tags: true
  excerpt_only: false

# Additional features
features:
  toc: true
  image_zoom: true
  code_highlight: true
  reading_time: true
  progress_bar: true
  back_to_top: true
  related_posts: true
  social_share: true
  dark_mode: true

# SEO settings
seo:
  enable: true
  twitter_card: summary_large_image
  facebook_insights: false
  google_analytics: false
  bing_verify: false

# Performance settings
performance:
  lazy_loading: true
  image_optimization: true
  minify_html: true
  preload_posts: true

# Archive settings
archive:
  enable: true
  permalink: /archive/
  layout: archive
  title: Blog Archive

# Comments settings (choose one)
comments:
  provider: disqus # false (default), "disqus", "giscus"
  disqus:
    shortname: # your shortname
  giscus:
    repo: # your repo
    repo_id: # your repo id
    category: # your category
    category_id: # your category id

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jim Jing"
      comments: true

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"
