# main text of home
title: Jim Jing
bio: Neuroscience Researcher | AI Enthusiast | Exploring Brain and Cognition

# twitter summary info
description: A personal academic website focusing on neuroscience research and artificial intelligence

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/self_picture.jpg

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: auto

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: false
resume-url: resume

# GitHub Pages configuration
url: https://junlinjing.github.io
baseurl: /jjing-neuro

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:title/
future: true

# GitHub Pages settings
github: [metadata]
lsi: false
safe: true
incremental: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Local development configuration (uncomment when needed)
#url: http://localhost:4000
#baseurl: ""

# Social links
twitter: JimJing1997
linkedin: jjunlin
github_username: https://github.com/JunlinJing
email: jjunlin197@163.com

# Academic links
googlescholar: citations?user=YOUR_SCHOLAR_ID
researchgate: Junlin-Jing
orcid: 0009-0006-1290-7445

# Website author information
authors:
  jimjing:
    name: Jim Jing
    bio: Neuroscience Researcher | AI Enthusiast | Exploring Brain and Cognition
    external-image: false
    picture: assets/images/self_picture.jpg
    twitter: JimJing1997

# Site width
width: large

# Pagination
pagination:
  enabled: false
  sort_reverse: true
  title: ":title"
  per_page: 5
  permalink: "/:num/"

# Pages
projects: true
publications: true
research: true
teaching: false
about: true
blog: true

# Post settings
read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true

# Jekyll plugins
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-sitemap

# HTML compression
compress_html:
  ignore:
    envs:
      - development
      - stage

# Include and exclude
include:
  - _pages
  - .nojekyll

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - .git/
  - .github/
  - .gitignore
  - .DS_Store
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata

# RSS Feed configuration
feed:
  path: feed.xml
  posts_limit: 20
  categories:
    - news
    - blog
  tags: true
  excerpt_only: false
